### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [givensuman/appa-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by givensuman** [comment]
Wow you're quick! I added what you were looking for and finalized some tweaks to the theme. Feel free to include it in your list if you like!

**Comment by unixorn** [comment]
I look for updates every day or two. This will be in today's PR
